name: media_picker_widget
description: A widget that picks media files from storage and allows you to place anywhere in the widget tree.
version: 0.0.4
homepage: https://github.com/rafid08/media_picker_widget

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  photo_manager: '>=1.0.0 <=1.2.0'
  sliding_up_panel: '>=1.0.1 <=2.0.0+1'
  image_picker: '>=0.6.0 <=0.7.5+3'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: