name: media_picker_widget
description: A widget that picks media files from storage and allows you to place anywhere in the widget tree.
version: 1.0.5
homepage: https://github.com/rafid08/media_picker_widget

environment:
  sdk: ">=2.12.0 <=3.10.1"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  photo_manager: ^2.7.2
  sliding_up_panel: ^2.0.0+1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: